### ISSUE TITLE
update bulma to 1.0

### ISSUE THREAD

**Issue by Wessie** [R-a-dio/valkyrie-themes#2]

**Comment by icxes** [comment]
Our dark theme now more or less works with 1.0 (on the public pages anyway). We could just disable the bulma native dark theme since it uses [this](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) to set itself as dark even when you choose light theme on the site depending on your browser/operating system preferences. [This](https://github.com/jgthms/bulma/blob/main/versions/bulma-no-dark-mode.scss) "should" do that, but I was either too braindead or too tired to figure out why it "didn't" when I tried.
